добавить возможность работать с коэффициентом мощности
insurance-product-comparisons/backend pull request #14
Opened 2023-12-06 09:58 UTC by Andrey-VU

Добавлена фича получения списка дто EnginePowerDto, содержащее поле "name" и "id" .
Сделан контроллер, сервис, модель, дто, настроен маппер

2023-12-06 13:12 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/model/PowerFactor.java
> +    private String power;
Здесь не хватает private Integer id для JPA.  

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

2023-12-06 13:15 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/model/PowerFactor.java
> +    private BigDecimal coefficient;
Опять же, вместо BigDecimal достаточно Double для значений диапазона 0,6 - 1,6

2023-12-06 13:23 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/mapper/PowerFactorMapper.java
> +    @Mapping(target = "coefficient", source = "coefficient")
Здесь не ошибка, а только уточнение: когда поля совпадают, MapStruct конвертирует сам без проблем. Так как у тебя EnginePowerDto и PowerFactor, которые ты конвертируешь, имеют одинаковое поле coefficient, это соответствие полей можно не указывать явно

2023-12-06 13:26 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/mapper/PowerFactorMapper.java
> +    EnginePowerDto makeEnginePowerDto(PowerFactor powerFactor);
Касательно названий: в документации MapStruct принято такое оформление: CarDto carToCarDto(Car car);
Предлагаю придерживаться такого же способа наименования методов - такие названия лучше отражают суть происходящего: из какого типа в какой мы переводим. 

Подробнее можно почитать в официальной документации с примерами: https://mapstruct.org/

2023-12-06 13:27 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/service/PowerFactorServiceImpl.java
> +    public List<EnginePowerDto> getListEnginePowerCoefficient() {
Отличная работа! Осталось поправить формат получаемой модели и ДТО

2023-12-06 13:34 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/controller/PowerFactorController.java
> +@AllArgsConstructor
Хорошая практика - логировать обращения к контроллеру, поэтому предлагаю его реализовать. 
У Lombok есть для этого подходящая аннотация - @Slf4j, которую можно повесить над объявлением класса контроллера. В этом случае чтобы реализовать логирование с фактом обращения перед тем как вернуть результат нужно написать log.info(), а внутрь поместить информативный текст. Например, log.info("Вызывается GET /power-factor"). Таким образом, если у нас возникнут сложности с поиском багов в дальнейшем, мы будем видеть цепочку вызовов в консоли приложения 

О том, в каком едином стиле мы будем писать логи поговорим позже, когда завершим эту задачу

2023-12-06 13:35 UTC, cptntotoro commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/insurance_project
Супер! Спасибо, что привел к единому стандарту!

2023-12-06 13:38 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/coefficients/repo/PowerFactorRepo.java
> +public interface PowerFactorRepo extends JpaRepository<PowerFactor, Long> {
Давай сделаем Integer для 6 строк таблицы :)

2023-12-06 13:43 UTC, cptntotoro commented on src/main/resources/schema.sql
> -CREATE TABLE IF NOT EXISTS users (
Не понимаю, зачем ты удалил таблицу users. Поясни, пожалуйста :)

2023-12-06 13:45 UTC, cptntotoro requested changes
Возвращаю на доработку. Нужно реализовать формат ДТО из постановки задачи в формате id и название. У тебя сейчас реализовано название и коэффициент. Кроме того, прошу ознакомиться с комментариями и учесть их в новом ПР. Если будут вопросы, обязательно обращайся!

2023-12-06 14:52 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/coefficients/model/PowerFactor.java
> +    private String power;
Точно. Изначально делал ид в виде сочетания мощности и коэффициента, потом схему поменял, а здесь забыл.
Только у меня идея ничего не подчёркивает здесь - ей всё нравится.
PS Можно даже byte использовать - обидно за него всегда. Он есть, а его никто не использует.

2023-12-06 14:54 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/coefficients/mapper/PowerFactorMapper.java
> +    @Mapping(target = "coefficient", source = "coefficient")
Спасибо, что такие моменты подчёркиваешь.

2023-12-06 15:04 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/coefficients/repo/PowerFactorRepo.java
> +public interface PowerFactorRepo extends JpaRepository<PowerFactor, Long> {
может всё же  byte ;)

2023-12-06 15:09 UTC, Andrey-VU commented on src/main/resources/schema.sql
> -CREATE TABLE IF NOT EXISTS users (
там была моковая таблица users, которую я создавал ещё на этапе генерации оболочки для нашего проекта. 
Чтобы пустое приложение скомпилировалось, нужно было, чтобы хоть какая-то таблица была в schema.sql и я бездумно шлёпнул создание таблицы юзерс, не имеющей отношение к нашему проекту. Поскольку сейчас уже есть таблицы реальные, я удалил этот моковый юзерс

2023-12-06 15:12 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/coefficients/repo/PowerFactorRepo.java
> +public interface PowerFactorRepo extends JpaRepository<PowerFactor, Long> {
шучу. сделал Integer

2023-12-12 11:42 UTC, nkorzh requested changes

2023-12-12 11:42 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/dto/EnginePowerDto.java
> +package ru.ya.insurance.coefficients.dto;
пакеты – написал общий комментарий

2023-12-12 11:42 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/mapper/EnginePowerMapper.java
> +@Mapper(componentModel = "spring")
дефолтную модель можно настроить в pom.xml чтобы не передавать ее в аргумент аннотации каждый раз

2023-12-12 11:42 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/service/EnginePowerService.java
> +    List<EnginePowerDto> getListEnginePowerDto();
дто в возврате сервиса

2023-12-12 11:42 UTC, nkorzh commented on src/main/java/ru/ya/insurance/controller/EnginePowerController.java
> +        log.info("Запуск метода GET//engine-power");
для спринга есть библиотечный механизм логирования запросов и ответов

2023-12-12 11:42 UTC, nkorzh commented on src/test/java/ru/ya/insurance/coefficients/service/EnginePowerServiceImplTest.java
> +    void getListEnginePowerDto() {
нужен тест, в том числе функциональный

2023-12-12 11:42 UTC, nkorzh commented on src/main/java/ru/ya/insurance/controller/EnginePowerController.java
> +    @GetMapping(value = "/engine-power/all")
uri метода не очень говорящее

2023-12-12 11:42 UTC, nkorzh commented on src/main/resources/schema.sql
> +    power varchar(20) NOT NULL,
очень плохо интерпретируется ограничение из текстовой строки
давайте сделаем min_power, max_power (включать или нет верхнюю границу – решите сами), а метод уже сам переведет это в текст в который хотите

2023-12-12 11:42 UTC, nkorzh commented on src/main/resources/schema.sql
> +    CONSTRAINT UQ_POWER_COEFFICIENT UNIQUE (COEFFICIENT)
??
есть ли метод на добавление этих engine_power? если да, кто его пользователь?
unique ограничение не дает информации о том, для любой ли мощности есть коэффициент, и единственный ли он

предлагаю подумать нужно ли оно вообще в бд или его достаточно прописать в виде бизнес-логики в сервисе

2023-12-13 07:22 UTC, cptntotoro approved these changes

2023-12-13 16:08 UTC, merged

2023-12-21 21:55 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/coefficients/mapper/EnginePowerMapper.java
> +@Mapper(componentModel = "spring")
Сделал! 👍