Feature/osago base rate
insurance-product-comparisons/backend pull request #15
Opened 2023-12-06 18:57 UTC by SergeiBrin

❤️

2023-12-06 20:30 UTC, EugeneP87 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Сереж, привет! У нас уже есть таблица Users...

2023-12-06 20:33 UTC, SergeiBrin commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Да, точно. Сейчас удалю лишнюю

2023-12-06 21:13 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    // Метод забирает из таблицы поля id и transportType.
про комментарии ли это или нет ... статья. 
https://habr.com/ru/articles/562938/

Сергей извини, комментарии на проекте это сильно плохой тон.
В свою очередь JavaDoc является хорошей альтернативой, загляни в любой базовый класс Java, это и есть тот самый чистый код.

2023-12-06 21:39 UTC, bannovdaniil reviewed
Спасибо за вклад в проект, Оставил немного комментариев,

2023-12-06 21:39 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    @Query("select new ru.ya.insurance.osago.model.VehicleTypeDto(br.id, br.transportType) " +
Возможно применение MapStruct  будет более читабельным и более прееисполуемым в коде в последстии.

2023-12-06 21:39 UTC, bannovdaniil commented on src/test/java/ru/ya/insurance/osago/service/OsagoServiceImplTest.java
> +        assertTrue(dtos.contains(typeDto1));
увидел где нужен equals... на мой взгляд, тут возможно True не совсем уместен, если у тебя equals Только на ID так и проверить только id этого будет достаточно... но это не точно ;)

2023-12-06 22:27 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    // Метод забирает из таблицы поля id и transportType.
✅

2023-12-06 22:30 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/service/OsagoServiceImpl.java
> +        log.info("Класс OsagoServiceImpl, метод getVehicleTypes(). " +
✅

2023-12-06 22:31 UTC, SergeiBrin commented on src/test/java/ru/ya/insurance/osago/controller/BaseRateControllerTest.java
> +    @MockBean
Бывает) Например у меня 😄

2023-12-06 22:31 UTC, SergeiBrin commented on src/test/java/ru/ya/insurance/osago/controller/BaseRateControllerTest.java
> +    private ObjectMapper mapper;
✅

2023-12-06 22:32 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/model/VehicleTypeDto.java
> +@EqualsAndHashCode(of = "id")
Переопределенный equals и hashcode никогда не лишний :)

2023-12-06 22:33 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    @Query("select new ru.ya.insurance.osago.model.VehicleTypeDto(br.id, br.transportType) " +
Возможно, но работает на одну миллионую секунды медленнее))))

2023-12-06 22:34 UTC, SergeiBrin commented on src/test/java/ru/ya/insurance/osago/service/OsagoServiceImplTest.java
> +        assertTrue(dtos.contains(typeDto1));
Переопределенный equals и hashcode никогда не лишний :)

2023-12-06 22:35 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    @Query("select new ru.ya.insurance.osago.model.VehicleTypeDto(br.id, br.transportType) " +
Да и ради такого простого действия - в одну строку - писать MapStruct показалось не нужным

2023-12-06 22:42 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/model/VehicleTypeDto.java
> +@EqualsAndHashCode(of = "id")
➖

2023-12-06 22:43 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/osago/repository/BaseRateRepository.java
> +    @Query("select new ru.ya.insurance.osago.model.VehicleTypeDto(br.id, br.transportType) " +
➖

2023-12-06 22:43 UTC, SergeiBrin commented on src/test/java/ru/ya/insurance/osago/service/OsagoServiceImplTest.java
> +        assertTrue(dtos.contains(typeDto1));
➖

2023-12-07 15:56 UTC, bannovdaniil commented
> Даниил жестко так меня прожарил. Но я оказался крепким орешком)))

зубы сломаешь об тебя :)

2023-12-12 12:00 UTC, nkorzh requested changes

2023-12-13 07:22 UTC, cptntotoro approved these changes

2023-12-13 16:17 UTC, merged

2023-12-21 22:02 UTC, EugeneP87 commented on src/main/resources/schema.sql
> +    transport_type  varchar(255) NOT NULL,
можно попробовать enum или отдельной таблицей transport_types и связать по id