Add rate coefficient
insurance-product-comparisons/backend pull request #17
Opened 2023-12-06 21:01 UTC by bannovdaniil

1. Расчет ОСАГО - Территориальный Коэффициент
2. Добавил контроллер 3 енд поинта

- /region-coefficient/all
- /region-coefficient/search?query=test
- /region-coefficient/{regionId}

3. добавил, схему БД region_coefficients
4. добавил, данные для базы region_coefficients
5. создал юнит тесты

2023-12-06 21:28 UTC, SergeiBrin requested changes

2023-12-06 21:28 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/coefficients/service/impl/RegionCoefficientServiceImpl.java
> +
Без private final?

2023-12-07 15:49 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/coefficients/model/dto/SubRegionOutDto.java
> + */
Андрей спасибо за замечание! @Data генерит лишний мусор, исправил.

2023-12-12 12:23 UTC, nkorzh requested changes

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/controller/RegionCoefficientController.java
> +        log.info("GET /region-coefficient/all");
про логи в общем комменте

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/controller/RegionCoefficientController.java
> +        if (regionId == null) {
уже есть аннотация, это точно нужно?

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/dto/RegionCoefficientOutDto.java
> +public class RegionCoefficientOutDto {
Out -> Response ?

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/dto/SubRegionOutDto.java
> +    private BigDecimal coefficientInclude;
from, to? не понятно что значит инклюдный и эксклюдный коэффициент

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/mapper/RegionMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
компонентную модель в pom.xml

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/repository/RegionCoefficientRepository.java
> +    List<ru.ya.insurance.coefficients.model.RegionCoefficient> findAllByNumber(String number);
название и сам запрос отличаются
можно ли просто сделать findAllByNumber без Query? либо назвать метод надо иначе

2023-12-12 12:23 UTC, nkorzh commented on src/main/resources/schema.sql
> +    number              varchar(20)   NOT NULL,
`number varchar(20)` ??

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/repository/RegionCoefficientRepository.java
> +public interface RegionCoefficientRepository extends JpaRepository<ru.ya.insurance.coefficients.model.RegionCoefficient, Long> {
import ru.ya.insurance.coefficients.model.RegionCoefficient;

2023-12-12 12:23 UTC, nkorzh commented on src/main/java/ru/ya/insurance/coefficients/service/impl/RegionCoefficientServiceImpl.java
> +        return dtoList;
- сервис возвращает дто
- внутри комбинирует сущность и дто

2023-12-12 17:27 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/coefficients/dto/SubRegionOutDto.java
> +    private BigDecimal coefficientInclude;
coefficient_exclude 'Коэффициент КТ для транспортных средств, за исключением Тракторы, самоходные дорожно-строительные';
coefficient_include 'Коэффициент КТ для Тракторы, самоходные дорожно-строительные';

2023-12-12 17:54 UTC, bannovdaniil commented on src/main/resources/schema.sql
> +    number              varchar(20)   NOT NULL,
Номер по порядку из Приложения №2 к Указанию Банка России от 28 июля 2020 года N 5515-У

2023-12-12 17:56 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/coefficients/repository/RegionCoefficientRepository.java
> +            WHERE LOWER(e.name) LIKE LOWER(CONCAT('%', :query, '%'))
I LIKE

2023-12-13 07:22 UTC, cptntotoro approved these changes

2023-12-13 08:04 UTC, SergeiBrin approved these changes

2023-12-13 16:05 UTC, merged