feat: adding KBM
insurance-product-comparisons/backend pull request #19
Opened 2023-12-06 22:54 UTC by EugeneP87

2023-12-07 16:18 UTC, bannovdaniil reviewed
Евгений спасибо за проделанную работу. Оставил немного комментариев.

2023-12-07 16:18 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/kbm/controller/KbmController.java
> +@Validated
Не совсем понял, зачем тут @Validated? внутри нет не одной валидации.

2023-12-07 16:18 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/kbm/controller/KbmController.java
> +    private KbmController(KbmService kbmService) {
Возможно воспользовавшись аннотацией @AllArgsConstructor , улучшится читаемость? а зачем конструктор приватный?

2023-12-07 16:18 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/kbm/mapper/KbmMapper.java
> +@Mapper
у нас спринг, могу предположить, что такая анотация с параметрами
@Mapper(componentModel = "spring")
будет более уместной. ;)

2023-12-07 19:55 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/kbm/controller/KbmController.java
> +@Validated
исправил

2023-12-07 19:55 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/kbm/controller/KbmController.java
> +    private KbmController(KbmService kbmService) {
исправил

2023-12-07 19:56 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/kbm/mapper/KbmMapper.java
> +@Mapper
согласен)

2023-12-12 12:53 UTC, nkorzh requested changes
посмотрите общие замечания пожалуйста

2023-12-12 12:53 UTC, nkorzh commented on src/main/java/ru/ya/insurance/kbm/controller/KbmController.java
> +    public List<KbmDto> getKbmDtoList() {
см общий комментарий

2023-12-12 12:53 UTC, nkorzh commented on src/main/java/ru/ya/insurance/kbm/mapper/KbmMapper.java
> +@Mapper(componentModel = "spring")
с общий коммент

2023-12-12 12:53 UTC, nkorzh commented on src/main/java/ru/ya/insurance/kbm/service/KbmService.java
> +    public List<KbmDto> getKbmDtoList() {
так не надо
см общий коммент

2023-12-12 12:53 UTC, nkorzh commented on src/main/resources/data.sql
> +    ('Класс M', 3.92),
нужно ли слово `Класс` в данных?

2023-12-13 15:58 UTC, merged