feat: adding Age Experience
insurance-product-comparisons/backend pull request #20
Opened 2023-12-07 00:34 UTC by EugeneP87

2023-12-07 16:23 UTC, bannovdaniil reviewed
Исправил пару комментариев.

2023-12-07 16:23 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/ageExperience/controller/AgeExperienceController.java
> +@Validated
@Validated зачем?

2023-12-07 16:23 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/ageExperience/mapper/AgeExperienceMapper.java
> +    AgeExperienceMapper INSTANCE = Mappers.getMapper(AgeExperienceMapper.class);
у нас на проекте SpringBoot , поэтому немного смущают такие конструкции.

2023-12-12 13:02 UTC, nkorzh requested changes

2023-12-12 13:02 UTC, nkorzh commented on src/main/resources/schema.sql
> +);
коэффициент определяется min/max стажем и min/max возрастом
почему бы их не положить сразу в эту таблицу? все запросы и код станет проще

2023-12-13 07:21 UTC, cptntotoro approved these changes

2023-12-13 15:51 UTC, merged