Restriction coefficient
insurance-product-comparisons/backend pull request #21
Opened 2023-12-07 20:20 UTC by cptntotoro

- Реализовать хранение коэффициента ограничений согласно данным таблицы https://docs.google.com/spreadsheets/d/1y5zMhhf09ZOQTm5SEyaw6jiJE1UUhGT65x3wThNS4iw/edit?usp=sharing
- Реализовать получение списка всех DTO в формате id, name для использования в выпадающем списке в форме на фронтенде

2023-12-07 20:55 UTC, SergeiBrin requested changes

2023-12-07 20:55 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/DriverNumberCoefficientController.java
> +
Может сделать общий путь @RequestMapping("/osago") ?

2023-12-07 20:55 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/DriverNumberCoefficientController.java
> +    public List<DriverNumberCoefficientDto> getAllDriverNumberCoefficientDto() {
А здесь @GetMapping("/driving-number-coefficient")

Еще можно, как вариант, ResponceEntity<Наш объект> использовать возвращаемым значением.
return new ResponseEntity<>(имя объекта, HttpStatus.OK);

2023-12-07 21:01 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/controller/DriverNumberCoefficientController.java
> +    public List<DriverNumberCoefficientDto> getAllDriverNumberCoefficientDto() {
Да, это хорошая практика, но в данном случае пользы от неё не вижу. 

Дело в том, что для метода GET мы не предусматриваем никакого иного статуса, кроме 200. В случае, если отвалится БД, то соответствующий Runtime провалится и без нас и вернет 500 статус.

Если бы нам потребовалось вернуть статус 201 или что-то из 40_, мы бы обязательно оборачивали в ResponseEntity

2023-12-07 21:02 UTC, cptntotoro commented on src/main/java/ru/ya/insurance/controller/DriverNumberCoefficientController.java
> +
Я буду объединять все результаты наших трудов в единый эндпоинт. Поэтому у него будет какой-то один конкретный путь. Какой конкретно - подумаю, когда буду объединять наши усилия :)

2023-12-07 21:10 UTC, bannovdaniil approved these changes
Хороший чистый код, ничего лишнего на мой взгляд, придрался только к сокращению, а так все супер!

2023-12-07 21:10 UTC, bannovdaniil commented on src/main/resources/schema.sql
> +    coeff_name varchar(100) NOT NULL,
Возможно, coefficient будет немного уместнее чем сокращение coeff .

2023-12-07 21:19 UTC, EugeneP87 approved these changes

2023-12-13 08:02 UTC, SergeiBrin approved these changes

2023-12-13 15:45 UTC, merged