feat: add New Insurance Request
insurance-product-comparisons/backend pull request #29
Opened 2023-12-15 22:52 UTC by EugeneP87

2023-12-18 11:45 UTC, Andrey-VU approved these changes
К себе не запуливал - не проверял запускаемость. 
 А зрительно все изменения выглядят уместно и вполне красиво. 
 Добавил пару косметических комметариев

2023-12-18 11:45 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/mapper/osago/NewInsuranceRequestMapper.java
> +@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
надо будет почитать про этот механизм. я пока не вникал в такой маппинг

2023-12-18 11:45 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/model/osago/NewInsuranceRequest.java
> +@Table(name = "new_insurance_request")
builder прикрутить для junit-тестов сразу можно.
с ним удобнее наполнять данными

2023-12-18 11:45 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/model/osago/NewInsuranceRequest.java
> +    @Column(name = "gift", columnDefinition = "BOOLEAN DEFAULT FALSE")
название поля ведёт речь про подарок. Не читая документацию могу многое нафантазировать, что это за поле и зачем оно здесь. Но уверен, что ошибусь.

2023-12-18 11:45 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/repository/osago/NewInsuranceRequestRepository.java
> +public interface NewInsuranceRequestRepository extends JpaRepository<NewInsuranceRequest, Long> {
Идеально! ;)

2023-12-18 11:45 UTC, Andrey-VU commented on src/main/java/ru/ya/insurance/model/osago/NewInsuranceRequest.java
> +    boolean isGift;
хм, точно в этом поле не нужен модификатор доступа, как у других, выше?

2023-12-18 11:52 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/NewInsuranceRequest.java
> +    @Column(name = "gift", columnDefinition = "BOOLEAN DEFAULT FALSE")
Это поле при дефолтном выборе - страховка для себя, либо можно выбрать как "страховка в подарок". Пожалуй, можно так и переименовать, спасибо, что обратил внимание!:)

2023-12-18 14:03 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/NewInsuranceRequest.java
> +    boolean isGift;
просмотрел, спасибо!:)

2023-12-18 19:11 UTC, bannovdaniil requested changes
Добрался до половины, честно скажу устал

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    @Pattern(regexp = "^[а-яА-Яa-zA-Z ]{10,50}$",
есть Size и как быть например с фамилиями через дефис? или если будет 10 пробелов.
или фамилией "Ян"?
нут нажен просто @NotBlank @NotNull

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    @Pattern(regexp = "^7[0-9]{10}$",
если 7 в начале то это скорее всего будет "+7" ?

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    @Pattern(regexp = "^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]+$",
в валидации есть спецальный шаблон для емайлов @Email

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    private boolean insuranceAsAGift = false;
false значение по умолчанию, зачем его указывать?

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/exception/ErrorHandler.java
> +            ValidationException.class,
Вот сюда эксепшен и прилитит, там в catch его не надо указывать.

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/exception/NotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
это делается в ErrorHandler

2023-12-18 19:11 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
а чем тебя не устроили стандартные 
            MethodArgumentNotValidException.class и         InvalidParameterException.class ?

2023-12-18 20:21 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    @Pattern(regexp = "^[а-яА-Яa-zA-Z ]{10,50}$",
допустимые символы были прописаны в ограничениях фич-листа, можно добавить дефис, согласен, но если проставить только @NotBlank @NotNull, то можно будет еще и цифры вводить, и спецсимволы, а этого бы не хотелось. Предлагаю уменьшить мин. длину поля и добавить дефис

2023-12-18 20:30 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +    @Pattern(regexp = "^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+\\.[a-zA-Z]+$",
да, но он позволяет ввести в базу адрес формата "a@a", т.е. без домена верхнего уровня

2023-12-18 20:38 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
да, можно обойтись

2023-12-19 04:33 UTC, bannovdaniil approved these changes

2023-12-21 18:07 UTC, kozjulia reviewed
Женя, прими и пойми =)

2023-12-21 18:07 UTC, kozjulia commented on src/main/java/ru/ya/insurance/service/osago/impl/NewInsuranceRequestServiceImpl.java
> +        NewInsuranceRequest newInsuranceRequest =
не поняла, что делает эта строка...new dto переводит сам в себя?

2023-12-21 18:07 UTC, kozjulia commented on src/main/java/ru/ya/insurance/service/osago/impl/NewInsuranceRequestServiceImpl.java
> +                newInsuranceRequestRepository.save(newInsuranceRequest));
Не поняла - ты возвращаешь new dto? не надо использовать одно дто для разных действий

2023-12-21 18:07 UTC, kozjulia commented on src/main/java/ru/ya/insurance/service/osago/impl/RegionCoefficientServiceImpl.java
>  import java.util.ArrayList;
Мне не нравится логика запрос, в запросе, в цикле и тд.. Здесь куча запросов, н+1, надо логику пересмотреть =)

2023-12-21 18:07 UTC, kozjulia commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS driver_number_coefficient
Вопрос наверное не конкретно к этой схеме. Почему не Liquibase ?

2023-12-21 20:44 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/controller/osago/OsagoController.java
>      private final KbmCoefficientServiceImpl kbmServiceImpl;
Согласен

2023-12-21 20:44 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/controller/osago/OsagoController.java
> +    private final NewInsuranceRequestServiceImpl newInsuranceRequestService;
👍

2023-12-21 21:07 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/controller/osago/OsagoController.java
>      public FormFilterInitDto getFilterInitDto() {
ты про маппинг?
https://github.com/insurance-product-comparisons/backend/pull/15#discussion_r1423885751

2023-12-21 21:08 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/dto/osago/AgeDto.java
>  @Setter
а что именно не так?

2023-12-21 21:11 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/dto/osago/AgeExperienceDto.java
> +import lombok.Setter;
запишем в бэклог)

2023-12-21 21:14 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/dto/osago/NewInsuranceRequestDto.java
> +
не могут, поля провалидированы, noargs убрал 👍

2023-12-21 21:16 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/Age.java
>  @AllArgsConstructor
убрал equals

2023-12-21 22:05 UTC, EugeneP87 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS driver_number_coefficient
пока не было времени на него, добавим в бэклог

2023-12-21 22:08 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/service/osago/impl/RegionCoefficientServiceImpl.java
>  import java.util.ArrayList;
можешь уточнить? я вижу только один метод, мб его уже отрефакторили...
public List<Region> findAll() { return regionRepository.findAll(); }

2023-12-21 22:09 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/service/osago/impl/NewInsuranceRequestServiceImpl.java
> +                newInsuranceRequestRepository.save(newInsuranceRequest));
скорректировал

2023-12-21 22:09 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/KbmCoefficient.java
> +@EqualsAndHashCode
ок

2023-12-21 22:11 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/EnginePowerCoefficient.java
>  @Table(name = "engine_power_coefficient")
👍

2023-12-21 22:13 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/osago/AgeExperienceCoefficient.java
> +@Builder
билдер попросили для тестов, по IDENTITY уточни плиз

2023-12-21 22:31 UTC, merged