Feature/insurance offers view
insurance-product-comparisons/backend pull request #30
Opened 2023-12-20 04:01 UTC by SergeiBrin

Всем хелоу, хакеры 🐰 

Фичу, которую мне предложила сделать Настя реализовал: 
[Вот ссылка](https://docs.google.com/document/d/1ssEA1ciEps-dZ75RbeLeS3aIKScX0yjSreA0M6fGi88/edit?usp=sharing) на док Насти.

Где-то мог сделать чуть иначе, а может и нет))). Но это нормально. Настя предупреждала, что могла что-то и не предусмотреть. А я предусматриваю всё всё всё 😆 

Для этой фичи я сделал новый пакет common - то есть «общее», так как данные фичи вроде как относятся ко всем видам страховок (осаго, каско, дмс и тд). Запросы к зависимым сущностям сделал через JOIN FETCH. Уверен, что в данном случае так лучше всего.  

Ну а остальные штучки можете посмотреть сами. Главное, поберегите нервы))))) 
Кстати, [вот ссылка](https://dbdiagram.io/d/Kartochka-predlozheniya-657f3a2856d8064ca0303361) на новые таблицы.

goodBye() {}

2023-12-20 18:36 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +@RequestMapping("/common")
а почему "/common", а не "company" ?

2023-12-20 18:37 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
не совсем логично приходят
/company/{companyId}/insurance/{insuranceId}
а в методе перевернуто.

2023-12-20 18:46 UTC, bannovdaniil requested changes
хороший код, есть небольшая путаница в параметрах
гдето (companyId, insuranceId);
а гдето наоборот, (insuranceId, companyId);

от чего будут ошибки в логике.

2023-12-20 18:46 UTC, bannovdaniil commented on src/main/java/ru/ya/insurance/service/common/impl/InsuranceOfferCardServiceImpl.java
> +    public Insurance findInsuranceOfferCardById(Long companyId, Long insuranceId) {
оО, так и есть перевернул параметры, тут Company потом insuranceId

2023-12-20 22:07 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/service/common/impl/InsuranceOfferCardServiceImpl.java
> +    public Insurance findInsuranceOfferCardById(Long companyId, Long insuranceId) {
✅

2023-12-20 22:08 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
✅

2023-12-20 22:08 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +@RequestMapping("/common")
Фиг знает)

2023-12-20 22:37 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +@RequestMapping("/common")
Попробовал переосмыслить путь и пакеты для новых классов.

2023-12-20 22:37 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +@RequestMapping("/common")
✅

2023-12-21 00:19 UTC, bannovdaniil approved these changes

2023-12-21 18:19 UTC, kozjulia reviewed
Сергей, немного замечаний =)

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/controller/insurance/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
Почему контроллер видит ентити?

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/mapper/insurance/InsuranceOfferCardMapper.java
> +    @Mapping(source = "description", target = "insuranceDescription")
а почему такие разные поля у ентити и дто?. весь смысл маппера теряется

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +@NoArgsConstructor
Много контрукторов, какие нужны для ентити? нет toString()

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
почему идентити? Продумай, какие поля нужны для иквалс и хэшкод

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/company/License.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
аналогичные замечания

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/insurance/Feature.java
> +@AllArgsConstructor
аналогично

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/insurance/Insurance.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
аналогично

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/insurance/RequiredDocument.java
> +@Setter
аналогично

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/model/insurance/ValidityPeriod.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
аналогично

2023-12-21 18:19 UTC, kozjulia commented on src/main/java/ru/ya/insurance/service/insurance/impl/InsuranceOfferCardServiceImpl.java
> +    public Insurance findInsuranceOfferCardById(Long insuranceId, Long companyId) {
insurance лишнее в названии

2023-12-21 18:19 UTC, kozjulia commented on src/main/resources/data.sql
> +VALUES ('Альфа', 'Альфа страхование - это уверенность', 5.0, 'logo/alpha.png'),
Начальные значения нужны зачем?. Почему не Liquibase ?

2023-12-21 19:36 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/controller/insurance/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
Ревьюер сказал, что модели нужно маппить в DTO - в контроллере

2023-12-21 19:38 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/mapper/insurance/InsuranceOfferCardMapper.java
> +    @Mapping(source = "description", target = "insuranceDescription")
Какие-то поля относятся к company, какие-то к insurance. Чтоб не было путаницы

2023-12-21 19:41 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Ну чтоб id увеличивалось автоматически. А как лучше? Я постарался продумать поля для equals и hashcode. А какие у тебя есть предложения?

2023-12-21 19:43 UTC, SergeiBrin commented on src/main/resources/data.sql
> +VALUES ('Альфа', 'Альфа страхование - это уверенность', 5.0, 'logo/alpha.png'),
Ну это якобы мы подтянули данные от страховых через их API

2023-12-21 19:44 UTC, SergeiBrin commented on src/main/resources/data.sql
> +VALUES ('Альфа', 'Альфа страхование - это уверенность', 5.0, 'logo/alpha.png'),
Не разбираюсь в этом - Liquibase, но поситаю. 😊

2023-12-21 19:49 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +@NoArgsConstructor
Для Entity нужен пустой конструктор и конструктор с параметрами

2023-12-21 19:51 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +@NoArgsConstructor
Но в целом, я просто скопировал аннотации с уже прошедших ревью моделей и добавил аннотации к полям, которые участвуют и не участвуют в equals и hashcode

2023-12-21 19:55 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/service/insurance/impl/InsuranceOfferCardServiceImpl.java
> +    public Insurance findInsuranceOfferCardById(Long insuranceId, Long companyId) {
А где именно и почему? Если скажешь где и почему, то я исправлю :)

2023-12-21 22:39 UTC, EugeneP87 approved these changes

2023-12-21 23:18 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/controller/common/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
Спорный момент. По идее по пути /company/{companyId}/insurance/ мы можем вытащить все страховки одной компании, а если наоборот - /insurance/{insuranceId}/company/ или /insurance/{insuranceId}/company/{companyId} - что это получается? Мб метод изменить?

2023-12-21 23:20 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/controller/insurance/InsuranceOfferCardController.java
> +        Insurance insurance = insuranceOfferService.findInsuranceOfferCardById(insuranceId, companyId);
ага, я Юле в другом PR ответил ссылкой на коммент ревьювера

2023-12-21 23:23 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/company/Company.java
> +@NoArgsConstructor
удалил
@EqualsAndHashCode(onlyExplicitlyIncluded = true)

2023-12-21 23:23 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/insurance/Feature.java
> +@AllArgsConstructor
удалил
@EqualsAndHashCode(onlyExplicitlyIncluded = true)

2023-12-21 23:23 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/insurance/ValidityPeriod.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
удалил
@EqualsAndHashCode(onlyExplicitlyIncluded = true)

2023-12-21 23:23 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/insurance/Insurance.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
удалил
@EqualsAndHashCode(onlyExplicitlyIncluded = true)

2023-12-21 23:24 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/company/License.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
удалил
@EqualsAndHashCode(onlyExplicitlyIncluded = true)

2023-12-21 23:42 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/repository/insurance/InsuranceRepository.java
> +    Optional<Insurance> findByIdAndCompanyId(Long insuranceId, Long companyId);
Сереж, такой вопрос: а нужна ли здесь @Query? 🤔

2023-12-21 23:49 UTC, EugeneP87 commented on src/main/java/ru/ya/insurance/model/company/License.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
вернул для тестов

2023-12-21 23:53 UTC, merged