Develop
insurance-product-comparisons/backend pull request #33
Opened 2023-12-22 06:48 UTC by EugeneP87

### Добавлена новая функциональность:

1. Пакет "newInsuranceRequest": "Создание заявки с описанием ситуации, если её нет в каталоге", [ссылка на ТЗ](https://docs.google.com/document/d/1mLDkJoQ8oGVjYOBk-w_tuwawR5KIbM0Xs8dlI-ESvf8/edit?pli=1#heading=h.zaexo44qsqti)
2. Пакет "insurance": "Просмотр карточки предложения "страхование ОСАГО", [ссылка на ТЗ](https://docs.google.com/document/d/1ssEA1ciEps-dZ75RbeLeS3aIKScX0yjSreA0M6fGi88/edit)
3. Пакет "consultation": "Заявка на консультацию", [ссылка на ТЗ](https://docs.google.com/document/d/1S7jVxwizJAurR7hgyirhOIWoInb9id4IDP_WGXPQ2Ko/edit?pli=1)

Также проведен рефакторинг и постарались устранить замечания по предыдущему ревью.

2023-12-23 14:00 UTC, nkorzh requested changes
Контроллеры: возвращают то dto то не dto
Сервисы: возвращают то модели то dto
Из названий некоторых дто непонятно, это запрос или ответ

тестов почти нет

2023-12-23 14:31 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/repository/insurance/InsuranceRepository.java
> +    Optional<Insurance> findByIdAndCompanyId(Long insuranceId, Long companyId);
Я думаю, что постоянная выборка может в следующий раз и не потребоваться.

2023-12-23 14:32 UTC, SergeiBrin commented on src/main/java/ru/ya/insurance/repository/insurance/InsuranceRepository.java
> +    Optional<Insurance> findByIdAndCompanyId(Long insuranceId, Long companyId);
Для другого рода запросов к этим таблицам

2023-12-23 14:33 UTC, SergeiBrin commented on src/test/java/ru/ya/insurance/service/insurance/impl/InsuranceOfferCardServiceImplIT.java
> +        Insurance getInsurance = service.findInsuranceOfferCardById(companyId, insuranceId);
Это я так хитро проверил метод сервиса - без моков)

2024-01-23 18:13 UTC, Andrey-VU approved these changes

2024-01-23 18:54 UTC, merged